apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: git@github.com:cristinagh4848/azure-argocd-gitops.git
      sshPrivateKeySecret:
        name: github-private-key
        key: privateKey
 
  # Enables application status badge feature
  statusbadge.enabled: "true"
